FROM amazoncorretto:21

WORKDIR /app

COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle.kts settings.gradle.kts ./
COPY src src

RUN ./gradlew build -x test --no-daemon

EXPOSE 8080

CMD ["./gradlew", "bootRun", "--args=--spring.profiles.active=local", "--no-daemon"]
